name: Melos Flutter Test Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  melos_flutter_tests:
    name: Run Melos Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Get dependencies
        run: |
          flutter pub global run melos bootstrap
          flutter pub global run melos pubget
          flutter pub global activate coverde
      - name: Analyze the project's Dart code
        run: flutter pub global run melos analyze

      - name: Run tests
        run: flutter pub global run melos test

      - name: Run tests coverage
        run: |
          flutter pub global run melos test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Update README
        run: |
          branch=$(echo "${GITHUB_REF#refs/heads/}")
          sed -i "s/:branch/$branch/g" README.md

      - name: Check commit message
        run: |
          if git log --format=%B -n 1 ${{ github.sha }} | grep -q '\[skip ci\]'; then
            echo "Skipping workflow execution due to [skip ci] commit message."
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git commit -am "Update branch name in README [skip ci]"
          git push