name: Melos Flutter Test Workflow

on:
  pull_request:
    branches:
      - '*'

jobs:
  melos_flutter_tests:
    name: Run Melos Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Get dependencies
        run: |
          flutter pub global run melos bootstrap
          flutter pub global run melos pubget
      - name: Analyze the project's Dart code
        run: flutter pub global run melos analyze

      - name: Run tests
        run: flutter pub global run melos test
      - name: Run tests coverage
        run: |
          flutter pub global run melos test-coverage